### ISSUE TITLE
supporting k3s as the hub server

### ISSUE THREAD

**Issue by hansongChina** [clusternet/clusternet#201]
When the application is deployed, system:anonymous is used, causing an error when the hub application is deployed to the Agent。
status:
  phase: Failure
  reason: please check whether the advertised apiserver of current child cluster is
    accessible. Unauthorized

**Comment by hansongChina** [comment]
K3s sets annoymous-auth to false by default
https://github.com/k3s-io/k3s/blob/f18b3252c0fbdfdc2a8e4d0a6d8deb4921052af9/pkg/daemons/control/server.go#L183-L185

**Comment by dixudx** [comment]
Yes, `k3s` sets `annoymous-auth` to `false` by default. And this flag can not be override.

when using k3s as the hub server, [curl with parentClusterToken](https://github.com/clusternet/clusternet/blob/main/docs/tutorials/visiting-child-clusters-with-rbac.md#using-curl) works. While the deployer inside of `clusternet-hub` still uses `system:anonymous`. This is the root cause.

Thanks for raising this issue. :+1::+1::+1:
