### ISSUE TITLE
clusternet agent  discoverClusterCIDR  failed

### ISSUE THREAD

**Issue by snstaberah** [clusternet/clusternet#372]
#### What would you like to be added:
![image](https://user-images.githubusercontent.com/8952747/173176767-88d93c04-151a-4162-a1fd-de2a65b3e13d.png)
clusternet-agent failed when  running  in a kubernetes  that apiserver、controller-manager、kube-scheduler run as a docker container or bin
#### Why is this needed:
add param to set cluster cidr、servicecidr ，so clusternet can manage a cluster that apiserver、controller-manager、kube-scheduler run as a docker container or bin，for example  rancher rke cluster /k3s cluster

![image](https://user-images.githubusercontent.com/8952747/173176900-2d804474-31a9-42df-a13e-0b436b162a57.png)

**Comment by dixudx** [comment]
@snstaberah Would you please submit a PR on fixing this?

> clusternet-agent failed when running in a kubernetes that apiserver、controller-manager、kube-scheduler run as a docker container or bin

Currently these kube pods are searched with label selectors, either `component=kube-apiserver` or `app.kubernetes.io/component=kube-apiserver`.  That's why `clusternet-agent` can not find `kube-apiserver` running as a separate docker container or binary process.

**Comment by snstaberah** [comment]
> @snstaberah Would you please submit a PR on fixing this?
> 
> > clusternet-agent failed when running in a kubernetes that apiserver、controller-manager、kube-scheduler run as a docker container or bin
> 
> Currently these kube pods are searched with label selectors, either `component=kube-apiserver` or `app.kubernetes.io/component=kube-apiserver`. That's why `clusternet-agent` can not find `kube-apiserver` running as a separate docker container or binary process.

ok  i think let user set these in agent env  is a solution，if agent can't find control-plan compent  as static pod,then agent  can  read  these  in  agent  env  param;
this  is  more effective than  try  to  find  those  param  automatically,because those  param is mostly static setted and seldom change, and there are  many  solutions  to install a kubernetes cluster,   write a automatic method to adapt them  one by one  is difficult;

**Comment by dixudx** [comment]
> there are many solutions to install a kubernetes cluster, write a automatic method to adapt them one by one is difficult;

I agree.

> i think let user set these in agent env is a solution，if agent can't find control-plan compent as static pod,then agent can read these in agent env param;
this is more effective than try to find those param automatically,because those param is mostly static setted and seldom change,

Sounds good. This provides a flexible way to find those pods. And I think static pods apply to this design as well. We can apply default environment values.

But what if those k8s components are running with binaries or docker containers ?

**Comment by dixudx** [comment]
Great! Let's do it in this way.
