### ISSUE TITLE
What are the differences compared to karmada？

### ISSUE THREAD

**Issue by victory460** [clusternet/clusternet#441]
This project is awesome and perfect.
What are the differences, advantages and disadvantages compared to [karmada](https://github.com/karmada-io/karmada)？

**Comment by dixudx** [comment]
@victory460 Thanks for your support on Clusternet.

Both Clusternet and Karmada are trying to solve the same problems, i.e., multiple Kubernetes cluster managements and cross-cluster application managements. But they are adopting different approaches. And they are using different design principles as well.

Clusternet is designed to be an add-on, which can be deployed easily like other add-on plugins, such as flannel, coredns. It helps extend existing Kubernetes cluster with multiple cluster capabilities. While Karmada adopts another approach, that is setting up a standalone and completed Kubernetes cluster (with etcd, kube-apiserver, kube-controller-manager, etc) exclusively for Karmada. That's why the hosting Kubernetes cluster can be registered as a child/member cluster in Clusternet, and Karmada can NOT.

They are quite a lot of feature differences between Clusternet and Karmada. You can learn more from [Clusternet Core Features](https://github.com/clusternet/clusternet#core-features).

**Comment by victory460** [comment]
Thanks a lot.

**Comment by victory460** [comment]
> @victory460 Thanks for your support on Clusternet.
> 
> Both Clusternet and Karmada are trying to solve the same problems, i.e., multiple Kubernetes cluster managements and cross-cluster application managements. But they are adopting different approaches. And they are using different design principles as well.
> 
> Clusternet is designed to be an add-on, which can be deployed easily like other add-on plugins, such as flannel, coredns. It helps extend existing Kubernetes cluster with multiple cluster capabilities. While Karmada adopts another approach, that is setting up a standalone and completed Kubernetes cluster (with etcd, kube-apiserver, kube-controller-manager, etc) exclusively for Karmada. That's why the hosting Kubernetes cluster can be registered as a child/member cluster in Clusternet, and Karmada can NOT.
> 
> They are quite a lot of feature differences between Clusternet and Karmada. You can learn more from [Clusternet Core Features](https://github.com/clusternet/clusternet#core-features).

> `That's why the hosting Kubernetes cluster can be registered as a child/member cluster in Clusternet, and Karmada can NOT.`
What this mean? Can you give a example for the scenes. @dixudx

**Comment by dixudx** [comment]
In Clusternet, a parent cluster can register itself as a child cluster. This brings a consistent cluster managements on all member clusters.

**Comment by victory460** [comment]
> In Clusternet, a parent cluster can register itself as a child cluster. This brings a consistent cluster managements on all member clusters.

Awesome, it look like a tree.

**Comment by victory460** [comment]
When the member cluster is deployed in a private environment (such as IDC),  only the main cluster exposed with public ip.
Can `clusternet` work fine for the situation? @dixudx

**Comment by dixudx** [comment]
> When the member cluster is deployed in a private environment (such as IDC), only the main cluster exposed with public ip. Can `clusternet` work fine for the situation? @dixudx

Sure. Only if the child clusters can visit the parent cluster, then all works well. Clusternet can manage all kinds of clusters, including clusters running at the edge, in private IDC, private/public clouds, or on your raspberry pi.

**Comment by victory460** [comment]
clusternet need [submariner](https://submariner.io/) to enables direct networking between Pods and Services in different Kubernetes clusters?

**Comment by dixudx** [comment]
> clusternet need [submariner](https://submariner.io/) to enables direct networking between Pods and Services in different Kubernetes clusters?

Submariner could work as an add-on to help extend the cross-cluster networking.
